---
.travis.yml:
  rubygems_api_key: "VyeqcD0wFqddh8+TJnkS2uL3S4MzXIDdEvhdYsQBynHuZSUMXtiUlfXTi0YMPzWVjqun8KQlm8stOyzwpoJZ4hDXLXLMuVdSM3/Ob1eLmIUtbIBkLuLYeD+coDHiz2Z8y36GiCaS/Fx9xZfCAmqYn+bnOl9pgNZhGFOWsQX2+3Y="
