language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.5
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: "VyeqcD0wFqddh8+TJnkS2uL3S4MzXIDdEvhdYsQBynHuZSUMXtiUlfXTi0YMPzWVjqun8KQlm8stOyzwpoJZ4hDXLXLMuVdSM3/Ob1eLmIUtbIBkLuLYeD+coDHiz2Z8y36GiCaS/Fx9xZfCAmqYn+bnOl9pgNZhGFOWsQX2+3Y="
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
